# NumPy
NumPy is a Python library, used for working with arrays, it is short for "Numerical Python".

In [3]:
import numpy

# Create a NumPy array:

In [ ]:
arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


# NumPy as np
NumPy is usually imported under the np alias

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# Dimensions in Arrays

In [ ]:
# 0d array
a = np.array(42)

# 1d array
b = np.array([1, 2, 3, 4, 5])

# 2d array
c = np.array([
              [1, 2, 3],
              [4, 5, 6],
              
              ])

# 3d array
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# check number of dimensions
print(f"{a.ndim} dimensions and a shape of {a.shape}")
print(f"{b.ndim} dimensions and a shape of {b.shape}")
print(f"{c.ndim} dimensions and a shape of {c.shape}")
print(f"{d.ndim} dimensions and a shape of {d.shape}")

0 dimensions and a shape of ()
1 dimensions and a shape of (5,)
2 dimensions and a shape of (2, 3)
3 dimensions and a shape of (2, 2, 3)


# Access Array Elements
The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [ ]:
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

print('Last element from 2nd row: ', arr[1, -1])

print('Elements from index 1 to index 4 from 2nd row', arr[1, 1:4])

2nd element on 1st row:  2
Last element from 2nd row:  10
Elements from index 1 to index 4 from 2nd row [7 8 9]


# Creating Arrays With a Defined Data Type

In [ ]:
'''
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
'''

# store the array as a string
arr = np.array([1, 2, 3, 4], dtype='i')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)


[1 2 3]
int32


# Reshape From 1-D to 2-D

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(3, 4)

print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Unknown Dimension

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3, -1)

print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

In [8]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [10]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7,8,9]])

arr = arr + np.array([1,0,1])
